### ISSUE TITLE
T-0.a Design student and job posting database schema (2 story points)

### ISSUE THREAD

**Issue by kadiralt** [L3CH3R0/somethingdank-soen341project2023#14]
The sub-tasks under this task include:
- Determine the fields together with their data types to be included in the student profile and job posting database tables.
- Design the database schema to store the data about students and job postings effectively.

**Comment by emeka-okechukwu** [comment]
The fields for the student table include:

- First name
- Last name
- Username
- Email address
- Password
- Avatar
- Bio
- Degree
- School
- Skills
- Resume

**Comment by emeka-okechukwu** [comment]
The fields for the job postings table include:

- Job ID
- Title
- Company name
- Job type
- Job Category
- Location
- Salary
- Description
- Requirements
- Application deadline
- Contact info
