### ISSUE TITLE
Log user stories and review (2 story points)

### ISSUE THREAD

**Issue by L3CH3R0** [L3CH3R0/somethingdank-soen341project2023#2]
Log in all 6 of our user stories and make sure that these are the proper user stories before committing.

**Comment by L3CH3R0** [comment]
Updated the first user story.

**Comment by Rubello21** [comment]
Added the second user story

**Comment by kadiralt** [comment]
Added the third user story

**Comment by j3rrimmy** [comment]
Added user story number 4

**Comment by emeka-okechukwu** [comment]
Added the fifth user story

**Comment by Abdel1107** [comment]
added the 6th user story
