### ISSUE TITLE
AT-1.2: Browsing Job Postings

### ISSUE THREAD

**Issue by L3CH3R0** [L3CH3R0/somethingdank-soen341project2023#30]
**Issue Tracking
This Acceptance test is for #9** 
1. User presses “Job Postings” 
2. User presses “Search Job Title” and searches for a specific job
     a.  User presses “Filter Button” to browse job postings
4. User presses on job that interests them and gets prompted with a description of the job

**Comment by emeka-okechukwu** [comment]
Marking as won't be fixed as we created another one
