### ISSUE TITLE
AT-1.1: Build Profile 

### ISSUE THREAD

**Issue by L3CH3R0** [L3CH3R0/somethingdank-soen341project2023#31]
**Issue Tracking
This Acceptance Test is for #8 
User Acceptance Flow** 
1. User presses “Profile” button on the upper navigation bar 
2. User presses “Choose File” button under “Change Avatar” and upload avatar image
    a. User presses “Remove File” to remove avatar image
3. User fills in “Bio” field 
4. User presses “Choose File” button under “Upload Resume” and uploads resume file
    a. User presses “Remove File” to remove resume file
5. User presses “Save Changes” button
6. User gets confirmation that “Your profile is updated successfully”

**Comment by emeka-okechukwu** [comment]
Marking as won't be fixed as we created another one
